insert all into base_data.tmg_task_cfg values
('01','AC001','AC','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=AC001')
into base_data.tmg_task_cfg values ('01','AC002','AC','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=AC002')
into base_data.tmg_task_cfg values ('01','AC003','AC','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=AC003')
into base_data.tmg_task_cfg values ('01','AS001','AS','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=AS001')
into base_data.tmg_task_cfg values ('01','AS101','AS','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=AS101')
into base_data.tmg_task_cfg values ('01','AS102','AS','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=AS102')
into base_data.tmg_task_cfg values ('01','AS103','AS','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=AS103')
into base_data.tmg_task_cfg values ('01','AS104','AS','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=AS104')
into base_data.tmg_task_cfg values ('01','AS105','AS','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=AS105')
into base_data.tmg_task_cfg values ('01','PT001','PT','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=PT001')
into base_data.tmg_task_cfg values ('01','PT002','PT','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=PT002')
into base_data.tmg_task_cfg values ('01','PT003','PT','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=PT003')
into base_data.tmg_task_cfg values ('01','PT004','PT','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=PT004')
into base_data.tmg_task_cfg values ('01','PT901','PT','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=PT901')
into base_data.tmg_task_cfg values ('01','PD001','PD','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=PD001')
into base_data.tmg_task_cfg values ('01','EV001','EV','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=EV001')
into base_data.tmg_task_cfg values ('01','EV002','EV','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=EV002')
into base_data.tmg_task_cfg values ('01','EV003','EV','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=EV003')
into base_data.tmg_task_cfg values ('01','EV004','EV','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=EV004')
into base_data.tmg_task_cfg values ('01','EV005','EV','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=EV005')
into base_data.tmg_task_cfg values ('01','EV101','EV','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=EV101')
into base_data.tmg_task_cfg values ('01','EV102','EV','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=EV102')
into base_data.tmg_task_cfg values ('01','EV103','EV','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=EV103')
into base_data.tmg_task_cfg values ('01','EV104','EV','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=EV104')
into base_data.tmg_task_cfg values ('01','EV105','EV','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=EV105')
into base_data.tmg_task_cfg values ('01','EV106','EV','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=EV106')
into base_data.tmg_task_cfg values ('01','EV107','EV','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=EV107')
into base_data.tmg_task_cfg values ('01','EV108','EV','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=EV108')
into base_data.tmg_task_cfg values ('01','EV201','EV','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=EV201')
into base_data.tmg_task_cfg values ('01','EV301','EV','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=EV301')
into base_data.tmg_task_cfg values ('01','AG001','AG','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=AG001')
into base_data.tmg_task_cfg values ('01','AG002','AG','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=AG002')
into base_data.tmg_task_cfg values ('01','AG003','AG','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=AG003')
into base_data.tmg_task_cfg values ('01','AG101','AG','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=AG101')
select 1 from dual;


insert all 
into base_data.tmg_task_cfg values ('02','MG001','MG','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py run_date={{ti.xcom_pull(task_ids=''start2check'')}} task_id=MG001')
into base_data.tmg_task_cfg values ('02','MG002','MG','','spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py TX_DATE={{ti.xcom_pull(task_ids=''start2check'')}} task_id=MG002')
;

[MONITOR]
MG001=spark-submit --master yarn --num-executors 10 --executor-memory 10g --executor-cores 16 /root/base_data/airflow_executor.py run_date={{ti.xcom_pull(task_ids='start2check')}} task_id=MG001
# CNT_MT=spark-sql --master yarn --num-executors 10 --executor-memory 10g  --executor-cores 16 --hiveconf spark.sql.shuffle.partitions=10 -f /root/base_data/scripts/sql/monitor/tmg_cnt_monitor.sql
MG002=python /root/base_data/airflow_hive_executor.py run_date={{ti.xcom_pull(task_ids='start2check')}} task_id=MG002
# CNT_RATIO_MT=hive -f /root/base_data/scripts/sql/monitor/tmg_cnt_ratio_monitor.sql
# CNT_RATIO_MT=spark-sql --master yarn --num-executors 10 --executor-memory 10g  --executor-cores 16 --hiveconf spark.sql.shuffle.partitions=10 -f /root/base_data/scripts/sql/monitor/tmg_cnt_ratio_monitor.sql